"""init schema

Revision ID: 2c6133818132
Revises: 
Create Date: 2026-07-14 16:33:39.548999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6133818132'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Xác thực + nhận mã đặt chỗ (BR-15)'),
    sa.Column('member_type', sa.Enum('member', 'guest', name='member_type_enum'), server_default='guest', nullable=False),
    sa.Column('rank', sa.String(length=20), nullable=True, comment='Chỉ để hiển thị (BR-20); giả định chỉ member có'),
    sa.Column('visit_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('ng_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True, comment='Lý do cấm - có hiển thị (BR-20)'),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_code', sa.String(length=20), nullable=False, comment='Mã cửa hàng'),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_code')
    )
    op.create_table('addon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False, comment='Bội số 15 phút'),
    sa.Column('price', sa.Integer(), nullable=False, comment='JPY'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('MOD(duration_min, 15) = 0', name='chk_addon_duration'),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_code', sa.String(length=30), nullable=True, comment='BE sinh: {yyyyMMdd}-{shop_code}-{random} (BR-12)'),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('party_size', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='1-3; >=2 là booking nhóm (BR-14)'),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', 'completed', 'no_show', name='booking_status_enum'), server_default='pending', nullable=False, comment='COMPLETED tự động +1 visit_count (BR-19); no_show: giả định'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('party_size BETWEEN 1 AND 3', name='chk_party_size'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_code')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False, comment='Bội số 15 phút'),
    sa.Column('price', sa.Integer(), nullable=False, comment='JPY'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('MOD(duration_min, 15) = 0', name='chk_course_duration'),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('therapist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='therapist_gender_enum'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('available', 'booked', name='slot_status_enum'), server_default='available', nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'slot_date', 'start_time', name='uq_slot')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'therapist', name='account_role_enum'), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=True, comment='Chỉ với role therapist'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapist.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('combo_restriction',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('addon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['addon_id'], ['addon.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'addon_id'),
    comment='BR-09: tổ hợp course + add-on KHÔNG được phép; bảng rỗng = mọi combo hợp lệ'
    )
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('guest_no', sa.Integer(), nullable=False, comment='Người thứ mấy trong nhóm (1..party_size)'),
    sa.Column('main_course_id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=True, comment='Chỉ định đích danh — chỉ booking 1 người (BR-04)'),
    sa.Column('therapist_gender', sa.Enum('male', 'female', name='reservation_therapist_gender_enum'), nullable=True, comment='Chỉ định theo giới tính — loại trừ với therapist_id'),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('therapist_id IS NULL OR therapist_gender IS NULL', name='chk_therapist_exclusive'),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['main_course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['time_slot.id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapist.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'guest_no', name='uq_reservation')
    )
    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapist.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('therapist_id', 'work_date', 'start_time', name='uq_shift')
    )
    op.create_table('reservation_addon',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('addon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['addon_id'], ['addon.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reservation_id', 'addon_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation_addon')
    op.drop_table('shift')
    op.drop_table('reservation')
    op.drop_table('combo_restriction')
    op.drop_table('account')
    op.drop_table('time_slot')
    op.drop_table('therapist')
    op.drop_table('course')
    op.drop_table('booking')
    op.drop_table('addon')
    op.drop_table('shop')
    op.drop_table('ng_list')
    op.drop_table('customer')
    # ### end Alembic commands ###
