"""doi comment cot price tu JPY sang VND

Revision ID: 2d8aac6cde1a
Revises: b7e1a4f92c30
Create Date: 2026-08-26 13:19:11.500198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d8aac6cde1a'
down_revision = 'b7e1a4f92c30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addon', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.INTEGER(),
               comment='VND',
               existing_comment='JPY',
               existing_nullable=False)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.INTEGER(),
               comment='VND',
               existing_comment='JPY',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.INTEGER(),
               comment='JPY',
               existing_comment='VND',
               existing_nullable=False)

    with op.batch_alter_table('addon', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.INTEGER(),
               comment='JPY',
               existing_comment='VND',
               existing_nullable=False)

    # ### end Alembic commands ###
